In [14]:
import pandas as pd

In [15]:
name = '3_xhl_imputMF_future'
df = pd.read_csv(f"F:\\geodata\\river_runoff_obs\\{name}.csv")

In [16]:
df.tail()

             time           pre        tm      tmax      tmin  dis  mon
50764  2100-12-27  1.550638e+00 -0.841248  0.803955 -3.533447  NaN  NaN
50765  2100-12-28  1.476001e-02 -2.486938 -1.406189 -3.865570  NaN  NaN
50766  2100-12-29  1.215770e-02 -3.094513 -1.394623 -4.438141  NaN  NaN
50767  2100-12-30  5.775117e-18 -3.621063 -1.390442 -6.525024  NaN  NaN
50768  2100-12-31  3.996725e-16 -6.392395 -4.481140 -7.806793  NaN  NaN

In [17]:
df.columns

Index(['time', 'pre', 'tm', 'tmax', 'tmin', 'dis', 'mon'], dtype='object')

In [18]:
# Set 'time' column as index if it isn't already
df['time'] = pd.to_datetime(df['time'])  # Ensure time is datetime
df.set_index('time', inplace=True)       # Set it as the index

# Resample from daily to monthly
resampled_df = df.resample('M').agg({
    'pre': 'sum',    # Sum for 'pre'
    'dis': 'sum',    # Sum for 'dis'
    'tm': 'mean',    # Mean for 'tm'
    'tmax': 'mean',  # Mean for 'tmax'
    'tmin': 'mean'   # Mean for 'tmin'
})

C:\Users\HP\AppData\Local\Temp\ipykernel_24652\1719873173.py:6: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  resampled_df = df.resample('M').agg({

In [23]:
resampled_df.tail()

                  pre  dis         tm       tmax       tmin
time
2100-08-31  75.226483  0.0  27.915453  37.498674  20.112175
2100-09-30  33.899863  0.0  23.649778  33.385788  15.510905
2100-10-31  20.071738  0.0  15.848458  23.133397   9.978278
2100-11-30  27.766116  0.0   5.458008   9.936769   1.875643
2100-12-31   6.957470  0.0   1.504612   4.744447  -1.166157

In [20]:
resampled_df.to_csv(f"F:\\geodata\\river_runoff_obs\\{name}_month.csv")

In [21]:
# Resample from daily to monthly
resampled_10d_df = df.resample('10D').agg({
    'pre': 'sum',    # Sum for 'pre'
    'dis': 'sum',    # Sum for 'dis'
    'tm': 'mean',    # Mean for 'tm'
    'tmax': 'mean',  # Mean for 'tmax'
    'tmin': 'mean'   # Mean for 'tmin'
})
resampled_10d_df

                  pre    dis         tm       tmax       tmin
time
1962-01-01   0.325837  281.8 -11.758535  -4.289080 -17.756866
1962-01-11   1.905653  261.4 -12.588716  -7.490951 -17.262302
1962-01-21   0.877961  288.3 -14.900295  -7.726932 -20.973214
1962-01-31   0.755048  312.1  -8.930458  -1.287600 -15.341023
1962-02-10   1.599839  260.1  -7.712287  -1.190318 -13.481534
...               ...    ...        ...        ...        ...
2100-11-13  13.197871    0.0   5.989035  10.503354   2.317389
2100-11-23   6.905253    0.0   3.159274   6.938254   0.473276
2100-12-03   0.124619    0.0   1.673209   5.112305  -1.459470
2100-12-13   3.491768    0.0   2.945975   6.698593   0.404324
2100-12-23   3.338401    0.0  -0.599877   1.636539  -2.888713

[5077 rows x 5 columns]

In [22]:
resampled_10d_df.to_csv(f"F:\\geodata\\river_runoff_obs\\{name}_10d.csv")