## This script is for read the RGI dbf file recoding the basins need to be validated

In [4]:
import pandas as pd
from dbfread import DBF
from simpledbf import Dbf5

PyTables is not installed. No support for HDF output.
SQLalchemy is not installed. No support for SQL output.

In [5]:
# Path to the .dbf file
dbf_path = r"C:\Users\HP\Documents\ArcGIS\Projects\LSTM_pre0\c13_rgi60_SpatialJoin.dbf"
dbf = Dbf5(dbf_path)

# Convert the .dbf file to a pandas DataFrame
RGI6_df  = dbf.to_dataframe()
RGI6_df.set_index('RGIId', inplace=True)

In [10]:
RGI6_df

,Join_Count,TARGET_FID,GLIMSId,BgnDate,EndDate,CenLon,CenLat,O1Region,O2Region,Area,...,Area_1,station,number,Perimeter,cluster,number_1,location,四源流,sankao_1,abbre
RGIId,,,,,,,,,,,,,,,,,,,,,
RGI60-13.00001,0,0,G079494E34471N,20000810,-9999999,79.49390,34.47130,13,5,0.432,...,0.0,NaN,0,0.0,0,0,0,0,NaN,NaN
RGI60-13.00002,1,1,G077951E35545N,20020802,-9999999,77.95130,35.54520,13,5,0.367,...,17400.6,卡群,21,1392.0,6,23,4,1,NaN,kq
RGI60-13.00003,1,2,G077930E35519N,20020802,-9999999,77.92950,35.51880,13,5,0.070,...,17400.6,卡群,21,1392.0,6,23,4,1,NaN,kq
RGI60-13.00004,1,3,G077924E35525N,20020802,-9999999,77.92370,35.52520,13,5,0.255,...,17400.6,卡群,21,1392.0,6,23,4,1,NaN,kq
RGI60-13.00005,1,4,G077914E35531N,20020802,-9999999,77.91410,35.53090,13,5,0.261,...,17400.6,卡群,21,1392.0,6,23,4,1,NaN,kq
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
RGI60-13.54427,0,54424,G085600E34405N,20060919,-9999999,85.60000,34.40500,13,8,0.919,...,0.0,NaN,0,0.0,0,0,0,0,NaN,NaN
RGI60-13.54428,0,54425,G085604E34434N,20060919,-9999999,85.60400,34.43400,13,8,18.056,...,0.0,NaN,0,0.0,0,0,0,0,NaN,NaN
RGI60-13.54429,0,54426,G085616E34403N,20060919,-9999999,85.61600,34.40300,13,8,6.607,...,0.0,NaN,0,0.0,0,0,0,0,NaN,NaN
RGI60-13.54430,0,54427,G085631E34371N,20060919,-9999999,85.63100,34.37100,13,8,0.329,...,0.0,NaN,0,0.0,0,0,0,0,NaN,NaN
RGI60-13.54431,0,54428,G072234E38780N,20000916,-9999999,72.23385,38.78024,13,2,663.729,...,0.0,NaN,0,0.0,0,0,0,0,NaN,NaN

In [11]:
for scenario in ["ssp" + str(x) for x in [ 126,245, 370, 585]]:
    print(scenario)
    peak_water_df = pd.read_csv(f"I:\\GlacierData\\peakwater\\R131415_glac_runoff_fixed_monthly_1set_2000_2100-{scenario}-Batch.csv", index_col=0)
    
    peak_water_df=peak_water_df[['BCC-CSM2-MR', 'CESM2', 'CESM2-WACCM', 'EC-Earth3', 'EC-Earth3-Veg', 'FGOALS-f3-L', 'GFDL-ESM4', 'INM-CM4-8', 'INM-CM5-0', 'MPI-ESM1-2-HR', 'MRI-ESM2-0', 'NorESM2-MM']].apply(pd.to_numeric, errors='coerce').astype('Int64')
    peak_water_df
    peak_water_df[scenario] = peak_water_df.median( axis=1)
    RGI6_df = RGI6_df.merge(peak_water_df[scenario], how='left', left_index=True, right_index=True)

ssp126
ssp245
ssp370
ssp585

In [12]:
RGI6_df

,Join_Count,TARGET_FID,GLIMSId,BgnDate,EndDate,CenLon,CenLat,O1Region,O2Region,Area,...,cluster,number_1,location,四源流,sankao_1,abbre,ssp126,ssp245,ssp370,ssp585
RGIId,,,,,,,,,,,,,,,,,,,,,
RGI60-13.00001,0,0,G079494E34471N,20000810,-9999999,79.49390,34.47130,13,5,0.432,...,0,0,0,0,NaN,NaN,2042.0,2048.5,2049.5,2046.0
RGI60-13.00001,0,0,G079494E34471N,20000810,-9999999,79.49390,34.47130,13,5,0.432,...,0,0,0,0,NaN,NaN,2042.0,2048.5,2049.5,2046.0
RGI60-13.00001,0,0,G079494E34471N,20000810,-9999999,79.49390,34.47130,13,5,0.432,...,0,0,0,0,NaN,NaN,2042.0,2048.5,2049.5,2046.0
RGI60-13.00001,0,0,G079494E34471N,20000810,-9999999,79.49390,34.47130,13,5,0.432,...,0,0,0,0,NaN,NaN,2042.0,2048.5,2049.5,2046.0
RGI60-13.00001,0,0,G079494E34471N,20000810,-9999999,79.49390,34.47130,13,5,0.432,...,0,0,0,0,NaN,NaN,2042.0,2048.5,2049.5,2046.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
RGI60-13.54427,0,54424,G085600E34405N,20060919,-9999999,85.60000,34.40500,13,8,0.919,...,0,0,0,0,NaN,NaN,2067.0,2072.0,2068.5,2062.5
RGI60-13.54428,0,54425,G085604E34434N,20060919,-9999999,85.60400,34.43400,13,8,18.056,...,0,0,0,0,NaN,NaN,2069.5,2088.0,2091.5,2085.5
RGI60-13.54429,0,54426,G085616E34403N,20060919,-9999999,85.61600,34.40300,13,8,6.607,...,0,0,0,0,NaN,NaN,2067.0,2086.5,2088.0,2080.0
RGI60-13.54430,0,54427,G085631E34371N,20060919,-9999999,85.63100,34.37100,13,8,0.329,...,0,0,0,0,NaN,NaN,2046.5,2059.5,2057.5,2052.0
RGI60-13.54431,0,54428,G072234E38780N,20000916,-9999999,72.23385,38.78024,13,2,663.729,...,0,0,0,0,NaN,NaN,2064.5,2090.0,2095.0,2095.0

In [13]:
name_RGI6_df = RGI6_df[['abbre'] + ["ssp" + str(x) for x in [ 126,245, 370, 585]]]

In [14]:
name_RGI6_df

               abbre  ssp126  ssp245  ssp370  ssp585
RGIId
RGI60-13.00001   NaN  2042.0  2048.5  2049.5  2046.0
RGI60-13.00001   NaN  2042.0  2048.5  2049.5  2046.0
RGI60-13.00001   NaN  2042.0  2048.5  2049.5  2046.0
RGI60-13.00001   NaN  2042.0  2048.5  2049.5  2046.0
RGI60-13.00001   NaN  2042.0  2048.5  2049.5  2046.0
...              ...     ...     ...     ...     ...
RGI60-13.54427   NaN  2067.0  2072.0  2068.5  2062.5
RGI60-13.54428   NaN  2069.5  2088.0  2091.5  2085.5
RGI60-13.54429   NaN  2067.0  2086.5  2088.0  2080.0
RGI60-13.54430   NaN  2046.5  2059.5  2057.5  2052.0
RGI60-13.54431   NaN  2064.5  2090.0  2095.0  2095.0

[66429 rows x 5 columns]

In [16]:
mean_name_df = name_RGI6_df.groupby(['abbre']).median()

In [17]:
mean_name_df

       ssp126  ssp245  ssp370  ssp585
abbre
dsk    2025.5  2027.0  2027.0  2027.0
hsg    2024.0  2023.0  2023.0  2023.0
kq     2055.0  2053.0  2056.0  2052.5
slglk  2037.0  2038.5  2042.0  2038.5
tgzlk  2065.0  2072.0  2068.0  2064.5
wlwt   2055.0  2053.0  2057.0  2054.0
xhl    2034.5  2038.5  2041.0  2038.0